services:
  db:
    image: postgres:17.4-alpine
    expose:
      - "5432"
    # ports:
    #   - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=broccoli
    networks:
      - broccoli_net
  migrator:
    image: migrate/migrate
    environment:
      - DB_DRIVER=postgres
    volumes:
      - ./migrations:/migrations
    depends_on:
      - db
    networks:
      - broccoli_net
    command: ["--path", "/migrations", "--database", "postgres://postgres:${POSTGRES_PASSWORD}@db:5432/broccoli?sslmode=disable", "up"]
  backend:
    build:
      context: ./backend
    ports:
      - "5050:5050"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - API_KEY=${API_KEY}
    depends_on:
      - migrator
    networks:
      - broccoli_net
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://backend:5050
      - PUBLIC_WS_URL=ws://localhost:5050/ws
      - API_KEY=${API_KEY}
      - ORIGIN=http://localhost:3000
    networks:
      - broccoli_net
networks:
  broccoli_net: {}
